config/routes.rb
Rails.application.routes.draw do
	
	root 'welcome#home'
	# get '/about', to: 'welcome#about'
	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'
	get    '/login', to: 'sessions#new'
  	post   '/login', to: 'sessions#create'
  	delete '/logout', to: 'sessions#destroy'

  	resources :exhibitions
	resources :comments
	resources :rsvps

	resources :users do
		resources :exhibitions 
	end

	resources :users do
		resources :rsvps 
	end

	resources :exhibitions do
		resources :comments
	end

	# resources :users do
	# 	resources :comments 
	# end
	
	

	get '/auth/facebook/callback' => 'sessions#create'
	get '/auth/github/callback' => 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord

	has_many :rsvps, :dependent => :destroy
	has_many :users, through: :rsvps
	
	has_many :comments, :dependent => :destroy
	has_many :users, through: :comments

	# has_many :artists
	# has_one :review
	
	# belongs_to :author, :class_name => 'User', optional: true

	# validates :name, presence: true
	validates :name, :description, presence: true
	validate :validate_end_at_before_start_at

	def address
		"#{self.street_address}, #{self.city}, #{self.state} #{self.zipcode}" 
	end

	def dates
		if start_at && end_at
			self.start_at.strftime('%B %d, %Y') + " - " + self.end_at.strftime('%B %d, %Y')
		end
	end

	def self.most_rsvp
		Exhibition.all.max_by do |exhibition|
			exhibition.rsvps.count
		end
	end

	def average_review_rating
		self.reviews.average(:rating)
	end


  	def validate_end_at_before_start_at
    	if end_at && start_at
      		errors.add(:end_at, "Error ") if end_at < start_at
    	end
    end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController

	def index
		# if params[:user_id]
		# 	@exhibitions = Exhibition.find(params[:user_id]).exhibitions
		# 	render json: @exhibitions
		# else
		# 	@exhibitions = Exhibition.all
		# 	render json: @exhibitions
		# end
		@exhibitions = Exhibition.order(created_at: :desc).page(params[:page])
	end

	def show
		@exhibition = Exhibition.find_by(id: params[:id])
		@rsvp = @exhibition.rsvps.build
		render json: @exhibition
		# @exhibition.dates
	end

	def new
		@exhibition = Exhibition.new
		# (author_id: current_user.id)
		# @exhibition.addresses.build
		# @exhibition.dates
		render json: @exhibition
	end

	def create
		@exhibition = Exhibition.new(exhibition_params)
		# byebug
		if @exhibition.save
			# redirect_to user_exhibitions_path, :notice => "Your Exhibition was added."
			# redirect_to @exhibition, :notice => "Your Exhibition was added."
			render json: @exhibition, status: 201
		else
			# render :new
			render json: @exhibition
		end
	end

	def edit 
		@exhibition = Exhibition.find_by(id: params[:id])
	end

	def update
		@exhibition = Exhibition.find_by(id: params[:id])
		if @exhibition.update(exhibition_params)
			redirect_to exhibitions_path, :notice => "Your Exhibition has been updated."
		else
			render :edit
		end
	end

	def destroy
		@exhibition = Exhibition.find_by(id: params[:id])
		@exhibition.delete
		redirect_to user_path(current_user), :notice => "Your Exhibition has been deleted."
		render json: @exhibition
	end

	private

	def exhibition_params
		params.require(:exhibition).permit(:name, :review, :description, :start_at, :end_at, :author_id, :street_address, :city, :state, :zipcode)
	end
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/_form.html.erb
 <%= form_for @exhibition do |f| %>
  <%= render '/error_messages' %>

  <%= f.label :title %>
  <%= f.hidden_field :author_id %>
  <%= f.text_field :name %><br>

  <%= f.label :body %>
  <%= f.text_area :description %><br>

  <label>Location:</label><br>
  <%= f.label :street %>
  <%= f.text_field :street_address %><br>
 
  <%= f.label :city %>
  <%= f.text_field :city %><br>
 
  <%= f.label :state %>
  <%= f.text_field :state %><br>
 
  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %>

  <label>Dates:</label><br>
  <%= f.label :start_at %>
  <%= f.date_select :start_at %><br>

  <%= f.label :end_at %>
  <%= f.date_select :end_at %>
  <br>

  <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/exhibitions/edit.html.erb
<h1>Edit an Exhibition</h1>
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
  <br>
 <%= render 'form' %>
  </div>
</div>

app/views/exhibitions/index.html.erb
<h1>Exhibitions</h1>
<%= page_entries_info @exhibitions %>
<%= paginate @exhibitions, window: 2 %>
<!-- paginate helper -->
	<% if @exhibitions.empty? %>
	No Exhibitions Found
	<% else %>

	<table>
		<tr>
			<th>Title</th>
			<th>Summary</th>
		</tr>
			<% @exhibitions.each do |exhibition| %>
		<tr>
			<th><%= exhibition.name.capitalize %></th>
			<td> <%= exhibition.description %> | <%= link_to "Show", exhibition_path(exhibition) %></td>
  		</tr>
  		<% end %>			
 	<% end %>
	</table>


	

app/views/exhibitions/new.html.erb
<h1>Add a New Exhibition</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <br>
  <%= render 'form' %>
  </div>
</div>

<!-- %= link_to 'Back to exhibition', exhibitions_path %>-->


	<script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
      //prevent form from submitting the default way
      event.preventDefault();
 
      var values = $(this).serialize();
 
      var posting = $.exhibition('/exhibitions', values);
 
      posting.done(function(data) {
        var post = data;
        $("#exhibitionTitle").text(exhibition["name"]);
        $("#exhibitionBody").text(exhibition["description"]);
      });
    });
  });
</script>

app/views/exhibitions/show.html.erb
<h3><%= @exhibition.name %></h3><br>
	
	<label>Description:</label> <%= @exhibition.description %><br><br>
	<label>Dates:</label> <%= @exhibition.dates %><br><br>
	<label>Location:</label> <%= @exhibition.address %><br>

	<% if !logged_in? %>
		<% else %>

		<label>Comments:</label><br>
		<% @exhibition.comments.each do |comment|%> 

			"<%= comment.content.capitalize%> " - by <%= comment.user.name%><br>

			<% end %>
			<%= link_to "Add comment", new_exhibition_comment_path(@exhibition, @exhibition.comments.build) %><br><br>

			<% if !logged_in? %>
			<% else %>
			
			<%= form_for @rsvp do |f|%>
    			<%= f.hidden_field :exhibition_id %>
    			<label>Are you Attending?</label>
					<%= f.collection_select(:status, ["Yes", "No", "Maybe"], :to_s, :to_s) %>
					<%= f.submit "RSVP to this Exhbition", :class => "btn btn-primary" %>
					<% end %>
				<% end %> 
			<% end %> <br>


			<%= link_to "Back to Exhibitions", exhibitions_path %>