config/routes.rb
Rails.application.routes.draw do
	
	root 'welcome#home'
	# get '/about', to: 'welcome#about'
	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'
	get    '/login', to: 'sessions#new'
  	post   '/login', to: 'sessions#create'
  	delete '/logout', to: 'sessions#destroy'

  	resources :exhibitions
	resources :comments
	resources :rsvps

	resources :users do
		resources :exhibitions 
	end

	resources :users do
		resources :rsvps 
	end

	resources :exhibitions do
		resources :comments
	end

	# resources :users do
	# 	resources :comments 
	# end
	
	

	get '/auth/facebook/callback' => 'sessions#create'
	get '/auth/github/callback' => 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	
	has_many :exhibitions

	has_many :rsvps
	has_many :exhibitions, through: :rsvps

	has_many :comments
	has_many :exhibitions, through: :comments

	validates :email, :presence => true
	validates :email, :uniqueness => true


	def self.find_or_create_by_omniauth(auth_hash)
		self.where(:email => auth_hash['info']['email']).first_or_create do |user|
			user.password = SecureRandom.hex
		end
	end

	def rsvps_count
		self.exhibitions.count
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

	def index
		@users = User.all
    render json: @users
	end

	def show
		@user = User.find_by(id: params[:id])
    @exhibitions = @user.exhibitions
    render json: @user
	end

	def new
    @user = User.new
    render json: @user
  end

  def create
    @user = User.new(user_params)
      if @user.save
        # login @user
        flash[:success] = "Welcome to St.Art App!"
        # redirect_to @user
        render json: @user
      else
        # render :new 
        render json: {errors: @user.errors.full_messages, status: :uprocessable_entity}
    end
  end

  def edit
    @user = User.find(params[:id])
    render json: @user
  end

  def update
    if @user.update(user_params)
      # redirect_to @user, notice: 'User was successfully updated.' 
      	render json: @user
        else
      	# render :edit
        render json: {errors: @user.errors.full_messages, status: :uprocessable_entity}
     	end
  end
  	
	private

	# Use callbacks to share common setup or constraints between actions.
	def set_user
		@user = User.find_by(id: params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% if @message %>
  <div class="center alert">
    <p><%= @message %></p>
  </div>
  <% end %>
  <div class="container">
  	<div class="row">
    	<h1>Users:</h1>
    		<h2><% @users.each do |user| %>      	
        	<%= link_to user.name, user_path(user) %><br> 
    		  <% end %><br> 
    	  </h2></div>
  	</div>
  </div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create Account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= link_to "Add Exhibition", new_exhibition_path %>
<h4><%= @user.name if @user.name %></h4>
<h2>Exhibitions You RSVP: </h2>
	<table>
		<tr>
		<% if @user.rsvps.empty? %>
			No Rsvps.
		<% else %>
			
			<th>Title</th>
			<th>Status</th>
			<th>Change Status</th>
			<th></th>
		</tr>
		
		<% @user.rsvps.each do |rsvp| %>
		<tr>
			<td><%= rsvp.exhibition_name  %></td>
		 	<td><%= rsvp.status %></td> 
		 	<td><%= link_to 'Edit', "/users/#{@user.id}/rsvps/#{rsvp.id}/edit" %></td>
  		</tr>	
  		<% end %>		
 		<% end %>
	</table><br>
	
	<h2>Exhibitions You Posted:</h2>
		<table>
			<tr>
			<% if @user.exhibitions.empty? %>
				No Exhibitions. 
			<% else %>
				<th>Title</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
			
			<% @user.exhibitions.each do |exhibition| %>
			<tr>
		 		<td><%= link_to exhibition.name, user_exhibition_path(@user, exhibition) %>| <%= link_to "Edit", edit_exhibition_path(exhibition) %> | <%= link_to "Remove", exhibition, method: :delete, data: {confirm: "Are you sure?"} %></td> 
		 		<% end %>			
 			<% end %>
  			</tr>
	</table>