config/routes.rb
Rails.application.routes.draw do
	
	root 'welcome#home'
	# get '/about', to: 'welcome#about'
	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'
	get    '/login', to: 'sessions#new'
  	post   '/login', to: 'sessions#create'
  	delete '/logout', to: 'sessions#destroy'

  	resources :exhibitions
	resources :comments
	resources :rsvps

	resources :users do
		resources :exhibitions 
	end

	resources :users do
		resources :rsvps 
	end

	resources :exhibitions do
		resources :comments
	end

	# resources :users do
	# 	resources :comments 
	# end
	
	

	get '/auth/facebook/callback' => 'sessions#create'
	get '/auth/github/callback' => 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "st.art app", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        
        <li><%= link_to "Exhibitions", exhibitions_path %></li>
       
        <% if logged_in? %>

          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "My Profile", user_path(current_user) %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>

          <% else %>

            <li><%= link_to "Join", new_user_path %></li>
            <li><%= link_to "Login", login_path %></li>
            <li><%= link_to("Login with Facebook", "/auth/facebook") %></li>
            <li><%= link_to("Login with Github", "/auth/github") %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>St.Art</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

    </div>
  </body>
</html>